/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package smart_agriculture_management_system;
import java.awt.CardLayout;
/**
 *
 * @author HP 850 G5
 */
public class FarmerForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FarmerForm.class.getName());
    CardLayout cardLayout;
    /**
     * Creates new form FarmerForm
     */
    public FarmerForm() {
        initComponents();
        
        // get layout from right panel
        cardLayout = (CardLayout) FRightPanel.getLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        FLeftPanel = new javax.swing.JPanel();
        jButtonFLLogout = new javax.swing.JButton();
        jButtonFLHome = new javax.swing.JButton();
        jButtonFLMyCorps = new javax.swing.JButton();
        jButtonFLCropHealth = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButtonFLHO = new javax.swing.JButton();
        jButtonFLReport = new javax.swing.JButton();
        jButtonFLProfile = new javax.swing.JButton();
        FRightPanel = new javax.swing.JPanel();
        FMyCorps = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jComboBoxFMCCropName = new javax.swing.JComboBox<>();
        jComboBoxFMCSeoson = new javax.swing.JComboBox<>();
        jTextFieldFMCField = new javax.swing.JTextField();
        jComboBoxFMCStatus = new javax.swing.JComboBox<>();
        jCalendarFMCExpectedHarvest = new com.toedter.calendar.JCalendar();
        jCalendarFMCPlantingDate = new com.toedter.calendar.JCalendar();
        jButtonFMCADD = new javax.swing.JButton();
        jButtonFMCDelete = new javax.swing.JButton();
        jButtonFMCUpdate = new javax.swing.JButton();
        jButtonFMCClear = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jComboBoxFMCUpdateID = new javax.swing.JComboBox<>();
        jLabel31 = new javax.swing.JLabel();
        jComboBoxFMCDeleteID = new javax.swing.JComboBox<>();
        jPanel11 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        FHome = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jPanel9 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        FHarverstOrder = new javax.swing.JPanel();
        FReports = new javax.swing.JPanel();
        FProfile = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(300, 200));
        setMaximumSize(new java.awt.Dimension(980, 545));
        setMinimumSize(new java.awt.Dimension(980, 545));
        setPreferredSize(new java.awt.Dimension(980, 545));
        setResizable(false);
        setSize(new java.awt.Dimension(980, 545));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(30, 30, 30));

        FLeftPanel.setBackground(new java.awt.Color(30, 30, 30));
        FLeftPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonFLLogout.setBackground(new java.awt.Color(30, 30, 30));
        jButtonFLLogout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonFLLogout.setForeground(new java.awt.Color(255, 255, 255));
        jButtonFLLogout.setText("Log Out");
        jButtonFLLogout.setAlignmentY(0.0F);
        jButtonFLLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFLLogoutActionPerformed(evt);
            }
        });
        FLeftPanel.add(jButtonFLLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 250, 35));

        jButtonFLHome.setBackground(new java.awt.Color(30, 30, 30));
        jButtonFLHome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonFLHome.setForeground(new java.awt.Color(255, 255, 255));
        jButtonFLHome.setText("Home");
        jButtonFLHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFLHomeActionPerformed(evt);
            }
        });
        FLeftPanel.add(jButtonFLHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 91, 250, 35));

        jButtonFLMyCorps.setBackground(new java.awt.Color(30, 30, 30));
        jButtonFLMyCorps.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonFLMyCorps.setForeground(new java.awt.Color(255, 255, 255));
        jButtonFLMyCorps.setText("My Corps");
        jButtonFLMyCorps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFLMyCorpsActionPerformed(evt);
            }
        });
        FLeftPanel.add(jButtonFLMyCorps, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 250, 35));

        jButtonFLCropHealth.setBackground(new java.awt.Color(30, 30, 30));
        jButtonFLCropHealth.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonFLCropHealth.setForeground(new java.awt.Color(255, 255, 255));
        jButtonFLCropHealth.setText("Crop Health");
        jButtonFLCropHealth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFLCropHealthActionPerformed(evt);
            }
        });
        FLeftPanel.add(jButtonFLCropHealth, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 250, 35));

        jPanel4.setBackground(new java.awt.Color(40, 40, 40));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        FLeftPanel.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 90));

        jButtonFLHO.setBackground(new java.awt.Color(30, 30, 30));
        jButtonFLHO.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonFLHO.setForeground(new java.awt.Color(255, 255, 255));
        jButtonFLHO.setText("Harvest & Order Management");
        jButtonFLHO.setAlignmentY(0.0F);
        jButtonFLHO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFLHOActionPerformed(evt);
            }
        });
        FLeftPanel.add(jButtonFLHO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 250, 35));

        jButtonFLReport.setBackground(new java.awt.Color(30, 30, 30));
        jButtonFLReport.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonFLReport.setForeground(new java.awt.Color(255, 255, 255));
        jButtonFLReport.setText("Reports");
        jButtonFLReport.setAlignmentY(0.0F);
        jButtonFLReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFLReportActionPerformed(evt);
            }
        });
        FLeftPanel.add(jButtonFLReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 250, 35));

        jButtonFLProfile.setBackground(new java.awt.Color(30, 30, 30));
        jButtonFLProfile.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonFLProfile.setForeground(new java.awt.Color(255, 255, 255));
        jButtonFLProfile.setText("Profile");
        jButtonFLProfile.setAlignmentY(0.0F);
        jButtonFLProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFLProfileActionPerformed(evt);
            }
        });
        FLeftPanel.add(jButtonFLProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 250, 35));

        FRightPanel.setBackground(new java.awt.Color(40, 40, 40));
        FRightPanel.setMaximumSize(new java.awt.Dimension(966, 508));
        FRightPanel.setLayout(new java.awt.CardLayout());

        FMyCorps.setBackground(new java.awt.Color(40, 40, 40));
        FMyCorps.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setBackground(new java.awt.Color(40, 40, 40));

        jPanel3.setBackground(new java.awt.Color(40, 40, 40));
        jPanel3.setMinimumSize(new java.awt.Dimension(680, 1820));
        jPanel3.setPreferredSize(new java.awt.Dimension(680, 1200));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("My Crops Management");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 440, -1));

        jPanel10.setBackground(new java.awt.Color(60, 60, 60));

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Field  ");

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Crop Name ");

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Expected Harvest");

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Seoson ");

        jLabel24.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Planting Date");

        jLabel25.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText(":");

        jLabel26.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Status ");

        jLabel27.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText(":");

        jLabel28.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText(":");

        jLabel30.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText(":");

        jComboBoxFMCCropName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBoxFMCSeoson.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTextFieldFMCField.setText("jTextField1");

        jComboBoxFMCStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButtonFMCADD.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonFMCADD.setText("ADD");
        jButtonFMCADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFMCADDActionPerformed(evt);
            }
        });

        jButtonFMCDelete.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonFMCDelete.setText("Delete");
        jButtonFMCDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFMCDeleteActionPerformed(evt);
            }
        });

        jButtonFMCUpdate.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonFMCUpdate.setText("Update");
        jButtonFMCUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFMCUpdateActionPerformed(evt);
            }
        });

        jButtonFMCClear.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonFMCClear.setText("Clear");
        jButtonFMCClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFMCClearActionPerformed(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("ID   : ");

        jComboBoxFMCUpdateID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel31.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("ID   : ");

        jComboBoxFMCDeleteID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jCalendarFMCPlantingDate, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel10Layout.createSequentialGroup()
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButtonFMCUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonFMCDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(46, 46, 46)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel31)
                                    .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(jCalendarFMCExpectedHarvest, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jComboBoxFMCDeleteID, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxFMCUpdateID, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jButtonFMCADD, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonFMCClear, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                            .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxFMCCropName, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxFMCSeoson, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldFMCField))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxFMCStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel25)
                    .addComponent(jComboBoxFMCCropName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel27)
                    .addComponent(jComboBoxFMCSeoson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel28)
                    .addComponent(jTextFieldFMCField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jLabel30)
                    .addComponent(jComboBoxFMCStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCalendarFMCExpectedHarvest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCalendarFMCPlantingDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jButtonFMCADD)
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonFMCUpdate)
                    .addComponent(jLabel29)
                    .addComponent(jComboBoxFMCUpdateID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonFMCDelete)
                    .addComponent(jLabel31)
                    .addComponent(jComboBoxFMCDeleteID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonFMCClear)
                .addContainerGap(147, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 630, 750));

        jPanel11.setBackground(new java.awt.Color(60, 60, 60));

        jLabel32.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Crop Table");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(249, 249, 249)
                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel32)
                .addContainerGap(358, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 850, 630, 420));

        jScrollPane2.setViewportView(jPanel3);

        FMyCorps.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 680));

        FRightPanel.add(FMyCorps, "card2");

        FHome.setBackground(new java.awt.Color(40, 40, 40));
        FHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(30, 30, 30));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("10");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 40, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smart_agriculture_management_system/wheat.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Order");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 97, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText(":");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 20, -1));

        FHome.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 290, 60));

        jPanel6.setBackground(new java.awt.Color(30, 30, 30));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("10");
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 40, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smart_agriculture_management_system/wheat.png"))); // NOI18N
        jLabel6.setText("jLabel2");
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 40));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Total Corps");
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 97, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText(":");
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 20, -1));

        FHome.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 290, 60));

        jPanel7.setBackground(new java.awt.Color(30, 30, 30));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("10");
        jPanel7.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 40, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smart_agriculture_management_system/wheat.png"))); // NOI18N
        jLabel10.setText("jLabel2");
        jPanel7.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 40));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Healthy Corps");
        jPanel7.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 97, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText(":");
        jPanel7.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 20, -1));

        FHome.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 290, 60));

        jPanel8.setBackground(new java.awt.Color(30, 30, 30));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("10");
        jPanel8.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 40, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smart_agriculture_management_system/wheat.png"))); // NOI18N
        jLabel14.setText("jLabel2");
        jPanel8.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 40));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Total Harvest");
        jPanel8.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 97, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText(":");
        jPanel8.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 20, -1));

        FHome.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 290, 60));

        jPanel2.setBackground(new java.awt.Color(60, 60, 60));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("About Us    :");

        jTextPane1.setBackground(new java.awt.Color(60, 60, 60));
        jTextPane1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextPane1.setForeground(new java.awt.Color(255, 255, 255));
        jTextPane1.setText("The Smart Agriculture Management System helps farmers manage crops, harvests, crop health, and buyer orders efficiently through a simple and modern digital platform. The system improves productivity and supports smart farming activities with an easy-to-use interface.");
        jScrollPane1.setViewportView(jTextPane1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel20)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        FHome.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, 310, 440));

        jPanel9.setBackground(new java.awt.Color(40, 40, 40));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smart_agriculture_management_system/Clean-Farm-Agriculture-Logo-Template-PNG-Transparent (1) (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        FHome.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 290, 100));

        FRightPanel.add(FHome, "card2");

        FHarverstOrder.setBackground(new java.awt.Color(40, 40, 40));
        FHarverstOrder.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        FRightPanel.add(FHarverstOrder, "card2");

        FReports.setBackground(new java.awt.Color(40, 40, 40));
        FReports.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        FRightPanel.add(FReports, "card2");

        FProfile.setBackground(new java.awt.Color(40, 40, 40));
        FProfile.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        FRightPanel.add(FProfile, "card2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(FLeftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FRightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FLeftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(FRightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 966, 508));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFLLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFLLogoutActionPerformed
    WelcomeForm login = new WelcomeForm();
    login.setVisible(true);

    this.dispose();    // TODO add your handling code here:
    }//GEN-LAST:event_jButtonFLLogoutActionPerformed

    private void jButtonFLHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFLHomeActionPerformed
    cardLayout.show(FRightPanel, "FHome");        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonFLHomeActionPerformed

    private void jButtonFLMyCorpsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFLMyCorpsActionPerformed
    cardLayout.show(FRightPanel, "FMyCorps");        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonFLMyCorpsActionPerformed

    private void jButtonFLCropHealthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFLCropHealthActionPerformed
    cardLayout.show(FRightPanel, "FMyCorps");        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonFLCropHealthActionPerformed

    private void jButtonFLHOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFLHOActionPerformed
    cardLayout.show(FRightPanel, "FMyCorps");        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonFLHOActionPerformed

    private void jButtonFLReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFLReportActionPerformed
    cardLayout.show(FRightPanel, "FMyCorps");        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonFLReportActionPerformed

    private void jButtonFLProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFLProfileActionPerformed
    cardLayout.show(FRightPanel, "FMyCorps");        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonFLProfileActionPerformed

    private void jButtonFMCADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFMCADDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonFMCADDActionPerformed

    private void jButtonFMCDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFMCDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonFMCDeleteActionPerformed

    private void jButtonFMCUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFMCUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonFMCUpdateActionPerformed

    private void jButtonFMCClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFMCClearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonFMCClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FarmerForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FHarverstOrder;
    private javax.swing.JPanel FHome;
    private javax.swing.JPanel FLeftPanel;
    private javax.swing.JPanel FMyCorps;
    private javax.swing.JPanel FProfile;
    private javax.swing.JPanel FReports;
    private javax.swing.JPanel FRightPanel;
    private javax.swing.JButton jButtonFLCropHealth;
    private javax.swing.JButton jButtonFLHO;
    private javax.swing.JButton jButtonFLHome;
    private javax.swing.JButton jButtonFLLogout;
    private javax.swing.JButton jButtonFLMyCorps;
    private javax.swing.JButton jButtonFLProfile;
    private javax.swing.JButton jButtonFLReport;
    private javax.swing.JButton jButtonFMCADD;
    private javax.swing.JButton jButtonFMCClear;
    private javax.swing.JButton jButtonFMCDelete;
    private javax.swing.JButton jButtonFMCUpdate;
    private com.toedter.calendar.JCalendar jCalendarFMCExpectedHarvest;
    private com.toedter.calendar.JCalendar jCalendarFMCPlantingDate;
    private javax.swing.JComboBox<String> jComboBoxFMCCropName;
    private javax.swing.JComboBox<String> jComboBoxFMCDeleteID;
    private javax.swing.JComboBox<String> jComboBoxFMCSeoson;
    private javax.swing.JComboBox<String> jComboBoxFMCStatus;
    private javax.swing.JComboBox<String> jComboBoxFMCUpdateID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextFieldFMCField;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
